- hosts: node
  remote_user: root
  tasks:
  - name: ssh
    shell: echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config  
  - name: sshd
    shell: "{{ item }}"
    with_items:
     - sed '/GSSAPIAuthentication/d' -i  /etc/ssh/sshd_config
     - sed '/UseDNS/d'  -i  /etc/ssh/sshd_config
     - echo "GSSAPIAuthentication no" >> /etc/ssh/sshd_config
     - echo "UseDNS no " >> /etc/ssh/sshd_config 
  - name: restart sshd
    service:
     name: "{{ item }}"
     state: restarted 
    with_items:
     - sshd
  - name: install packages
    yum:
     name: "{{ item }}"
     state: present
    with_items:
     - 'unzip'
     - 'gcc'
     - 'gcc-c++'
     - 'ksh'
     - 'compat-libcap1'
     - 'compat-libstdc++-33'
     - 'libaio-devel'
    tags:
      - rpm
  - name: create
    file:
     path: "{{ item }}"
     state: directory
     mode: 0755
    with_items:
     - /u01
  - name: group
    group:
     name: "{{ item }}"
     state: present
    with_items:
     - oinstall
     - dba
     - oper
  - name: user
    user:
     name: "{{ item }}"
     group: oinstall
     groups: oinstall,dba,oper
     uid: 1000
     state: present
    with_items:
     - oracle
  - name: change name
    raw: "echo {{hostname|quote}} > /etc/hostname"
  - name:
    shell: hostname {{hostname|quote}}
  - name: hostname
    shell: hostname 
    tags:
     - hostname
  - name: desktop1  yum groupinstall "GNOME Desktop" "Graphical Administration Tools" -y
    yum:
      name: "{{ item }}"
    with_items:
      - '@^gnome-desktop-environment'
      - '@Graphical Administration Tools'
    tags:
      - desktop1
    ignore_errors: True
  - name: desktop2
    shell: ln -sf /lib/systemd/system/runlevel5.target /etc/systemd/system/default.target
    tags:
      - desktop2
  - name: copy
    copy:
       src: /opt/
       dest: /u01/
       mode: 0777
    tags:
     - copy
