- hosts: node
  remote_user: root
  tasks:
  - name: mkdir
    file:
      path: /u01/soft
      state: directory
      mode: 0755
      owner: oracle
      group: oinstall
  - name: unzip 
    unarchive: 
      src: "{{ item }}" 
      dest: /u01/soft
      remote_src: yes
      owner: oracle
      group: oinstall
      mode: 01777
    with_items:
       - /u01/12c/V46095-01_1of2.zip
       - /u01/12c/V46095-01_2of2.zip
       - /u01/12c/V840019-01.zip
