- hosts: node
  remote_user: root
  tasks:
  - name: install expect
    yum: 
      name: expect
      state: present
  - name: rm file
    file:
      name: "{{ item }}"
      state: absent
    with_items:
      - /tmp/update.sh
    tags:
     - rm
  - name: echo \n is EOF
    shell: echo "{{ item }}" >> /tmp/update.sh
    with_items:
      - '#!/usr/bin/expect'
      - 'set timeout 5'
      - 'spawn passwd oracle' 
      - 'expect \"New password:\"'
      - 'send wRG2EM%F!pG3XpgZnwcz\n'
      - 'expect \"Retype new password:\"'
      - 'send wRG2EM%F!pG3XpgZnwcz\n'
      - 'interact'
  - name: chmod chown
    file:
      name: "{{ item }}"
      mode: 0777
      owner: root
      group: root
    with_items:
      - /tmp/update.sh
  - name: rm file
    file:
      name: "{{ item }}"
      state: absent
    with_items:
      - /tmp/update.sh
    tags:
     - rm
